# Generated by Django 5.2.6 on 2025-09-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("payments", "Payment"), ("fine", "Fine")],
                        default="payments",
                        max_length=10,
                    ),
                ),
                (
                    "money_to_pay",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "session_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
        ),
    ]
