# Generated by Django 5.2.6 on 2025-09-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0002_borrowing"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="session_uri",
        ),
        migrations.AddField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="library.borrowing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="session_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
