# Generated by Django 5.2.6 on 2025-09-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0002_remove_payment_session_uri_payment_borrowing_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="type",
        ),
        migrations.AddField(
            model_name="payment",
            name="fine_days",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
